apiVersion: v1
kind: Service
metadata:
  name: instantboard-client
  labels:
    run: instantboard-client
spec:
  # type: NodePort
  type: LoadBalancer
  selector:
    run: instantboard-client
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
