export default {
  FETCH_LABEL: '__FETCH_LABEL',
  FETCH_LABEL_SUCCESS: '__FETCH_LABEL_SUCCESS',
  CREATE_LABEL: '__CREATE_LABEL',
  CREATE_LABEL_SUCCESS: '__CREATE_LABEL_SUCCESS',
  UPDATE_LABEL: '__UPDATE_LABEL',
  UPDATE_LABEL_SUCCESS: '__UPDATE_LABEL_SUCCESS',
  DESTROY_LABEL: '__DESTROY_LABEL',
  DESTROY_LABEL_SUCCESS: '__DESTROY_LABEL_SUCCESS',
};
