export default {
  // LABEL
  FETCH_LABEL: '__FETCH_LABEL',
  FETCH_LABEL_SUCCESS: '__FETCH_LABEL_SUCCESS',
  FETCH_LABEL_FAILURE: '__FETCH_LABEL_FAILURE',

  CREATE_LABEL: '__CREATE_LABEL',
  CREATE_LABEL_SUCCESS: '__CREATE_LABEL_SUCCESS',
  CREATE_LABEL_FAILURE: '__CREATE_LABEL_FAILURE',

  UPDATE_LABEL: '__UPDATE_LABEL',
  UPDATE_LABEL_SUCCESS: '__UPDATE_LABEL_SUCCESS',
  UPDATE_LABEL_FAILURE: '__UPDATE_LABEL_FAILURE',

  DESTROY_LABEL: '__DESTROY_LABEL',
  DESTROY_LABEL_SUCCESS: '__DESTROY_LABEL_SUCCESS',
  DESTROY_LABEL_FAILURE: '__DESTROY_LABEL_FAILURE',

  SORT_LABEL: '__SORT_LABEL',
  SORT_LABEL_SUCCESS: '__SORT_LABEL_SUCCESS',
  SORT_LABEL_FAILURE: '__SORT_LABEL_FAILURE',

  // TASK
  FETCH_TASK: '__FETCH_TASK',
  FETCH_TASK_SUCCESS: '__FETCH_TASK_SUCCESS',
  FETCH_TASK_FAILURE: '__FETCH_TASK_FAILURE',

  CREATE_TASK: '__CREATE_TASK',
  CREATE_TASK_SUCCESS: '__CREATE_TASK_SUCCESS',
  CREATE_TASK_FAILURE: '__CREATE_TASK_FAILURE',

  UPDATE_TASK: '__UPDATE_TASK',
  UPDATE_TASK_SUCCESS: '__UPDATE_TASK_SUCCESS',
  UPDATE_TASK_FAILURE: '__UPDATE_TASK_FAILURE',

  DESTROY_TASK: '__DESTROY_TASK',
  DESTROY_TASK_SUCCESS: '__DESTROY_TASK_SUCCESS',
  DESTROY_TASK_FAILURE: '__DESTROY_TASK_FAILURE',

  SORT_TASK: '__SORT_TASK',
  SORT_TASK_SUCCESS: '__SORT_TASK_SUCCESS',
  SORT_TASK_FAILURE: '__SORT_TASK_FAILURE',

  POLL_TASK_SUCCESS: '__POLL_TASK_SUCCESS',
  POLL_TASK_FAILURE: '__POLL_TASK_FAILURE',

  // MEMBER
  FETCH_MEMBER: '__FETCH_MEMBER',
  FETCH_MEMBER_SUCCESS: '__FETCH_MEMBER_SUCCESS',
  FETCH_MEMBER_FAILURE: '__FETCH_MEMBER_FAILURE',

  // USER
  GET_USER: '__GET_USER',
  GET_USER_SUCCES: '__GET_USER_SUCCESS',
  GET_USER_FAILURE: '__GET_USER_FAILURE',

  UPDATE_USER: '__UPDATE_USER',
  UPDATE_USER_SUCCES: '__UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILURE: '__UPDATE_USER_FAILURE',

  DELETE_USER: '__DELETE_USER',
  DELETE_USER_SUCCES: '__DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: '__DELETE_USER_FAILURE',

  // REQUEST
  FETCH_REQUEST: '__FETCH_REQUEST',
  FETCH_REQUEST_SUCCESS: '__FETCH_REQUEST_SUCCESS',
  FETCH_REQUEST_FAILURE: '__FETCH_REQUEST_FAILURE',

  UPDATE_REQUEST: '__UPDATE_REQUEST',
  UPDATE_REQUEST_SUCCESS: '__UPDATE_REQUEST_SUCCESS',
  UPDATE_REQUEST_FAILURE: '__UPDATE_REQUEST_FAILURE',

  POLL_REQUEST_SUCCESS: '__POLL_REQUEST_SUCCESS',
  POLL_REQUEST_FAILURE: '__POLL_REQUEST_FAILURE',
};
