export default {
  LOGIN_ACTIVITY: '__LOGIN_ACTIVITY',
  USER_ACTIVITY: '__USER_ACTIVITY',
  MAIN_ACTIVITY: '__MAIN_ACTIVITY',
  TASK_ACTIVITY: '__TASK_ACTIVITY',
  LABEL_ACTIVITY: '__LABEL_ACTIVITY',
};

